version: '3'

services:
  postgres:
    image: mdillon/postgis
    volumes:
      - ./database/sql:/sql
      - ./database/sql/init.sql:/docker-entrypoint-initdb.d/z_init.sql
    environment:
      - POSTGRES_PASSWORD=postgres
    # ports:
    #   - '5432:5432'
  api:
    build:
      context: ./
    restart: always
    environment:
      # NOTE: AWS_ Variables provided by execution role in deployed version
      - AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
      - AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      - AWS_DEFAULT_REGION=us-east-1
      - INSTRUMENTATION_APPLICATION_KEY=appkey
      - INSTRUMENTATION_AUTH_DISABLED=False
      - INSTRUMENTATION_AUTH_JWT_MOCKED=True
      - INSTRUMENTATION_AWS_S3_REGION=us-east-1
      - INSTRUMENTATION_AWS_S3_BUCKET=corpsmap-data
      - INSTRUMENTATION_AWS_S3_ENDPOINT=http://minio:9000
      - INSTRUMENTATION_AWS_S3_DISABLE_SSL=True
      - INSTRUMENTATION_AWS_S3_FORCE_PATH_STYLE=True
      - INSTRUMENTATION_LAMBDACONTEXT=false
      - INSTRUMENTATION_DBUSER=instrumentation_user
      - INSTRUMENTATION_DBPASS=password
      - INSTRUMENTATION_DBNAME=postgres
      - INSTRUMENTATION_DBHOST=postgres
      - INSTRUMENTATION_DBSSLMODE=disable
      - INSTRUMENTATION_HEARTBEATKEY=password
      - INSTRUMENTATION_ROUTE_PREFIX=/instrumentation
    ports:
      - '80:80'
  minio:
    image: minio/minio
    environment:
      - MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
      - MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    command: server /data
    ports:
      - '9000:9000'
  # configure minio on startup (create buckets, etc)
  # inspired by https://github.com/minio/minio/issues/4769
  # and         https://gist.github.com/haxoza/22afe7cc4a9da7e8bdc09aad393a99cc
  minio_init:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      echo 'sleeping for 10 seconds while minio starts...';
      sleep 10;
      /usr/bin/mc config host add minio http://minio:9000 AKIAIOSFODNN7EXAMPLE wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY;
      /usr/bin/mc mb   minio/corpsmap-data-incoming   minio/corpsmap-data;
      /usr/bin/mc policy set public minio/corpsmap-data;
      /usr/bin/mc cp --recursive /media/projects/ minio/corpsmap-data/instrumentation/projects/ ;
      exit 0;
      "
    volumes:
      - ./data:/media
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@postgres.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    ports:
      - '8081:80'
  # Seed data using container was required as the sql file was so large
  # that it caused the postgres init to hang and exit early.
  seed_data:
    image: python:3
    depends_on:
      - api
      - postgres
    volumes:
      - ./_utils/seed_measurements:/app
    environment:
      - INSTRUMENTATION_API_HOST=instrumentation-api_api_1
      - INSTRUMENTATION_DBUSER=instrumentation_user
      - INSTRUMENTATION_DBPASS=password
      - INSTRUMENTATION_DBNAME=postgres
      - INSTRUMENTATION_DBHOST=instrumentation-api_postgres_1
      - INSTRUMENTATION_ROUTE_PREFIX=/instrumentation
    entrypoint: >
      /bin/sh -c "
      pip3 install requests psycopg2;
      python3 /app/generate_seed_measurements.py
      exit 0;
      "
