version: "3"

services:
  postgres:
    image: mdillon/postgis
    volumes:
      - ./database/sql:/sql
      - ./database/sql/init.sql:/docker-entrypoint-initdb.d/z_init.sql
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  api:
    build:
      context: ./
    environment:
      - INSTRUMENTATION_LAMBDACONTEXT=false
      - INSTRUMENTATION_SKIPJWT=true
      - INSTRUMENTATION_DBUSER=instrumentation_user
      - INSTRUMENTATION_DBPASS=password
      - INSTRUMENTATION_DBNAME=postgres
      - INSTRUMENTATION_DBHOST=postgres
      - INSTRUMENTATION_DBSSLMODE=disable
      - INSTRUMENTATION_HEARTBEATKEY=password
    ports:
      - "80:80"
  minio:
    image: minio/minio
    environment:
      - MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
      - MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    command: server /data
    ports:
      - "9000:9000"
  # configure minio on startup (create buckets, etc)
  # inspired by https://github.com/minio/minio/issues/4769
  # and         https://gist.github.com/haxoza/22afe7cc4a9da7e8bdc09aad393a99cc    
  minio_init:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      echo 'sleeping for 10 seconds while minio starts...';
      sleep 10;
      /usr/bin/mc config host add minio http://minio:9000 AKIAIOSFODNN7EXAMPLE wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY;
      /usr/bin/mc mb   minio/corpsmap-data-incoming   minio/corpsmap-data;
      /usr/bin/mc policy set public minio/corpsmap-data;
      /usr/bin/mc cp --recursive /media/projects/ minio/corpsmap-data/instrumentation/projects/ ;
      exit 0;
      "
    volumes:
      - ./data:/media
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@postgres.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    ports:
      - "8081:80"
