version: "3"

services:
  postgres:
    image: mdillon/postgis
    volumes:
      - ./database/sql:/sql
      - ./database/sql/init.sql:/docker-entrypoint-initdb.d/z_init.sql
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  api:
    build:
      context: ./
    environment:
      - INSTRUMENTATION_LAMBDACONTEXT=false
      - INSTRUMENTATION_SKIPJWT=true
      - INSTRUMENTATION_DBUSER=instrumentation_user
      - INSTRUMENTATION_DBPASS=password
      - INSTRUMENTATION_DBNAME=postgres
      - INSTRUMENTATION_DBHOST=postgres
      - INSTRUMENTATION_DBSSLMODE=disable
      - INSTRUMENTATION_HEARTBEATKEY=password
    ports:
      - "80:80"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@postgres.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    ports:
      - "8081:80"
