FROM registry1.dso.mil/ironbank/google/golang/golang-1.19:1.19.9 AS builder
WORKDIR /go/src/app

ENV CGO_ENABLED=0

COPY . .
RUN GOOS=linux GOARCH=amd64 \
    go build -ldflags="-w -s" -mod=vendor -o /go/bin/midas-telemetry

FROM registry1.dso.mil/ironbank/docker/scratch:ironbank
COPY --from=builder /go/bin/midas-telemetry /go/bin/midas-telemetry
ENTRYPOINT ["/go/bin/midas-telemetry"]
