FROM registry1.dso.mil/ironbank/google/golang/golang-1.19:1.19.9 AS builder
WORKDIR /go/src/app

ENV CGO_ENABLED=0
COPY go.* ./
RUN go mod download

COPY . .
RUN GOOS=linux GOARCH=amd64 \
    go build -ldflags="-w -s" -o /go/bin/midas-api

FROM registry1.dso.mil/ironbank/docker/scratch:ironbank
COPY --from=builder /go/bin/midas-api /go/bin/midas-api
ENTRYPOINT ["/go/bin/midas-api"]
