name: Pull Request CI

on:
  pull_request:
    branches: [develop]
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

jobs:
  PullRequestCI:
    name: Pull Request CI
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    env:
      DOCKER_BUILDKIT: 1

    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: |
          cp .example.env .env
          ./compose.sh test
