name: Pull Request CI

on:
  pull_request:
    branches: [develop]

jobs:
  PullRequestCI:
    name: Pull Request CI
    runs-on: ubuntu-latest

    env:
      DOCKER_BUILDKIT: 1

    steps:
      - uses: actions/checkout@v2

      - name: Run Tests
        run: ./compose.sh test
