name: Pull Request CI

on:
  pull_request:
    branches: [develop]

jobs:
  PullRequestCI:
    name: Pull Request CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker Compose
        run: |
          docker-compose up -d
          # Give it time to start up our API image
          sleep 5
      - name: Run Tests
        run: ./test.sh
