name: Pull Request CI

on:
  pull_request:
    branches: [develop]
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:
jobs:
  PullRequestCI:
    name: Pull Request CI
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    env:
      DOCKER_BUILDKIT: 1

    steps:
      - uses: actions/checkout@v2
      # Go needed to pull peer dependencies with go mod vendor
      - uses: actions/setup-go@v4
        with:
          go-version-file: "telemetry/go.mod"

      - name: Run Tests
        run: ./compose.sh test
